### PR TITLE
fixed scrolling transitions to the same map. closes #924

### LINKED ISSUE #924: Crash when scrolling from a map to itself
Put a scrolling teletransporter on the side of the map, and set the destination map as the same one.
Crash when teletransporting:
Fatal: Missing previous surface for scrolling

### PR DESCRIPTION
**Pull request by stdgregwar**
Fixed the inability to teleport to the same map with a scrolling transition. This closes #924.

### CODE REVIEW

File: src/core/Game.cpp [hunk 1]
```diff
@@ -479,24 +489,14 @@ void Game::update_transitions() {
             Transition::Direction::OPENING,
             this
         ));
+        if(needs_previous_surface) transition->set_previous_surface(previous_map_surface.get());
```
Comment (christopho) [inline src/core/Game.cpp]: Coding style

    if (needs_previous_surface) {
        ...
    }

**Comment by christopho** [comment]
Maps transitions are a fragile area of the code, we need good unit tests.
Can you update the existing unit test `teletransportation_tests` please? Thanks

**Review by christopho — CHANGES_REQUESTED** [review]

**Comment by christopho** [comment]
Please also update the changelog file.
